### ISSUE TITLE
No JSON based social syntax

### ISSUE THREAD

**Issue by melvincarvalho** [aaronpk/webmention#39] opened 2016-05-24 06:05 UTC
The WG [charter](https://www.w3.org/2013/socialweb/social-wg-charter) states:

> A JSON-based syntax to allow the transfer of social information

Yet I was unable to locate any JSON based examples in the text (tho perhaps I missed something)

Could this be made available for review?

**Comment by akuckartz** [comment] 2016-05-24 06:33
JSON-LD please.

**Comment by sandhawke** [comment] 2016-05-24 13:39
Hmm.    This is going to require some discussion.

Charter issues aside, can you provide a use case where json (or json-ld) would be overwhelmingly better than form encoding?   I say "overwhelmingly", because  I think it's clear from current adoption that form encoding works well for this, and also that having only one mandated syntax works well.

**Comment by aaronpk** [comment] 2016-05-24 16:00
The Webmention spec itself does not claim to implement the "social syntax" part of the charter. Webmention can be used with JSON documents, as is described in [3.2.2 Verification](https://www.w3.org/TR/webmention/#webmention-verification). Additionally, there has already been an implementation using Webmention with JSON-LD, which is thoroughly documented at http://lombardpress.org/2016/04/16/iiif-webmentions/

**Comment by melvincarvalho** [comment] 2016-05-24 16:20
It's kind of hard to leave the charter aside.  Because I think that it was hard to come to consensus on anything in the group, but the one thing we did come to consensus on was that we'd like to be using JSON to be passing things around.

So the main motivation for this is interoperability.  The social web benefits from more participants to grow the network effect.  I think this is especially true in this group where the large W3C members have mostly not joined meaning we are largely a grass roots effort working with organic growth rather than widespread adoption (id be happy to be corrected, if that's not accurate).

So the case for interoperability means that we stand a stronger chance by working together with a common ground.  The issue with form variables is that the namespaces are stripped off and need to be obtained out of band (by reading the spec) and then hard coded.  That's going to make interop with systems like Solid (or anything following W3C RECs) that much harder.

Why not have two examples implementors can use, one in JSON and one with form encoded variables?

**Comment by aaronpk** [comment] 2016-05-24 16:24
What I mean is that Webmention does not (and should not) define the social syntax. That's why we have Activity Streams 2.0 for example. We've already seen that Webmention can be used by JSON-based systems (JSON-LD even), so I don't see the problem here. If more implementations start using Webmention with JSON documents, then it may warrant adding some explicit examples to the spec.

**Comment by aaronpk** [comment] 2016-05-24 16:27
There was some previous discussion within the group about using JSON for the actual Webmention payload itself, but we ended up resolving not to go down that path: https://github.com/aaronpk/webmention/issues/4

**Comment by kevinmarks** [comment] 2016-05-24 16:40
The charter also says "Each of these technologies should not be tightly-coupled but can allow general purpose use." Melvin is proposing tight coupling here.

**Comment by sandhawke** [comment] 2016-05-24 17:11
@melvincarvalho I'm not asking you to forget about the charter, I'm asking you to keep the two issues separate.   Would it help to give them different issue numbers?

On the non-charter issue, you start to make a case, but I don't personally find it compelling, and I'm a huge fan of JSON and/or RDF.   I don't see where there's a big payoff in Webmention using JSON as its payload.   Solid, for example, seems to have decided not to use Webmention at all, **not** because of the lack of RDF payload, but because posts are authenticated anyway so the payload is encouraged to be more than a mention.

On the charter issue, at W3C, interpretation of the charter is up the group chair(s).   I just met with the chairs and they agreed with the position @aaronpk stated above, that it's the social syntax (that is, AS2) that needs to be in JSON, not that every protocol has to use JSON payloads for everything.  So Webmention using form-encoding instead of JSON does not violate the charter.

**Comment by melvincarvalho** [comment] 2016-05-24 22:41
@sandhawke being not a big fan of RDF, JSON ([or even of solid](https://www.w3.org/2015/06/23-social-irc)) makes it slightly challenging for me to feel encouraged that we can have an unbiased and productive conversation, but we can give it a try!

Re: splitting the issue into 2, we could do that, if you feel it's a good idea.  I'll try and keep the points separate then.

In terms of the charter, thanks for talking to the chairs, Im not sure I agree that this interpretation represents consensus of the group.  I would be interested to understand the position of other members of the WG / W3C.  

Re: interoperability, I felt I gave a compelling reason, namely the network effect.  Dont you think that multiple communities working with a common ground have a better chance of success?  

I dont see how solid could even theoretically use webmention when it uses syntactic sugar instead of namespaces, and the namespaces are communicated out of bound, in the spec.  I think the point here is that using existing web standards and W3C RECs, as Solid does, greatly increases interop.

Introducing a new system is just a pain for hetrogeneous systems that might have wanted to cooperate but now have an unreasonably high bar.  Isnt the point of W3C RECs so that, if you follow them you'll be able to interop with other systems much more easily.  This work seems to be balkanizing, rather than, bringing systems together.  Worse still, those that are following existing w3c recommendations (which is a lot of work) are seemingly penalized!

**Comment by melvincarvalho** [comment] 2016-05-24 23:15
Let me perhaps ask a slightly different way.  Is there already an example of a W3C REC where form encoded variables are passed around?  I would find it instructive to review, if so.

**Comment by sandhawke** [comment] 2016-05-24 23:19
I'm not sure how you read, "I'm a huge fan of JSON and/or RDF" and concluded I wasn't one.

Also, that's not how bias works.

**Comment by sandhawke** [comment] 2016-05-24 23:27
I have no idea what W3C REC use form-encoding aside from HTML.   I think HTML is enough.

> " I would be interested to understand the position of other members of the WG / W3C."

That's not how interpreting charters works.    If you left interpretation of the charter to the group, then the group could re-interpret its charter at will.

> I dont see how solid could even theoretically use webmention when it uses syntactic sugar instead of namespaces, and the namespaces are communicated out of bound, in the spec.

Well, back before Webmention went to CR, when it could have potentially been changed, the solid folks discussed it and decided they weren't interested in pursuing a Webmention-like solution.

It could be done in a backward compatible way -- and still could -- by defining a form-encoding-to-RDF mapping, basically borrowing JSON-LD.   And like JSON-LD, where the context MAY be specified by the protocol context, one could define a default @context for the webmention protocol.

One could do all of that, but frankly Webmention is so easy to implement, there's just no motivation, as far as I can see.

**Comment by melvincarvalho** [comment] 2016-05-25 00:20
> I'm not sure how you read, "I'm a huge fan of JSON and/or RDF" and concluded I wasn't one.

> I'm suspect if you search the minutes of the thousands of Working Group meetings I've participated in, you could also find me saying I'm not a fan of RDF. That's kind of a love/hate relationship. But I'm definitely a fan of JSON.

@sandhawke Im really sorry for my misreading of this.  It's late here and I've been multi tasking.  Total apologies.  I guess we've had one on one conversations about RDF in the past, and that put the idea in my head.  Not an excuse, sorry anyway.  I hope my following comments, could be taken at face value.

**Comment by melvincarvalho** [comment] 2016-05-25 00:44
> It could be done in a backward compatible way -- and still could -- by defining a form-encoding-to-RDF mapping, basically borrowing JSON-LD. And like JSON-LD, where the context MAY be specified by the protocol context, one could define a default @context for the webmention protocol.

Nice idea.  But I wonder if this would actually work?  Because JSON-LD distinguishes between literals and URIs eg using JSON objects.  Is the same possible with form encoded URIs.  

At this point I feel that using an existing REC such as JSON-LD, Turtle, RDF/XML etc. is a superior choice.  I dont think Solid (and other implementations) should forced to change to support form encoded variables, in order to interop.  Surely if the argument is that webmention is easy to implement, it's also easy to implement in JSON too, and its incumbent on the system to justify why web standards are not being reused, when this could easily happen, and allow an increased network effect?

**Comment by melvincarvalho** [comment] 2016-05-25 00:46
> Well, back before Webmention went to CR, when it could have potentially been changed, the solid folks discussed it and decided they weren't interested in pursuing aligning with Webmention.

FWIW I did raise this a couple of times I think on the mailing list in July of last year.

**Comment by sandhawke** [comment] 2016-05-25 00:53
Form encoding is clearly a standard.     It's not as flexible as JSON, but Webmention doesn't need that flexibility.

One can't just *add* JSON to Webmention without making dozens of implementors change their code if they want to stay in compliance.    And you haven't actually said anything that would be easier for anyone if they did.

**Comment by melvincarvalho** [comment] 2016-05-25 06:40
So Im saying to make those small changes, which in the vast majority of cases affect only one user, to resuse an existing W3C REC, rather than create a new system.  

I think we're possibly going round in circles when I say webmention is breaking interop with standards compliance systems (eg solid), and you saying that standards compliant systems dont want to be interop.  

If form encoded variables are going to become part of a W3C REC, it's something new (at least to me), and it seems to me we should solve the problem in a generic way ie in a way that is universal, extensible, interoperable etc.  If it's not something new, I'd love to be pointed to where it's been done before, that'd be a great precedent.

I've not yet seen a good argument for not using standards, for this use case.  I suppose that widespread adoption could be one such reason.  But I think adoption is small, perhaps less than 0.01% of the social web?  I guess Im asking what is the this should be a W3C recommendation and not a note, when it breaks interop with existing standards.

**Comment by kevinmarks** [comment] 2016-05-25 07:06
On 24 May 2016 11:40 pm, "Melvin Carvalho" <notifications@github.com> wrote:

> So Im saying to make those small changes, which in the vast majority of
> cases affect only one user, to resuse an existing W3C REC, rather than
> create a new system.
>
> I think we're possibly going round in circles when I say webmention is
> breaking interop with standards compliance systems (eg solid), and you
> saying that standards compliant systems dont want to be interop.
>
> If form encoded variables are going to become part of a W3C REC, it's
> something new (at least to me), and it seems to me we should solve the
> problem in a generic way ie in a way that is universal, extensible,
> interoperable etc. If it's not something new, I'd love to be pointed to
> where it's been done before, that'd be a great precedent.
>
well, it started in 1993 in HTML+:

https://www.w3.org/MarkUp/HTMLPlus/htmlplus_42.html

It was in HTML3

https://www.w3.org/MarkUp/html3/forms.html

HTML4

https://www.w3.org/TR/html4/interact/forms.html

and HTML5

 https://www.w3.org/TR/html5/forms.html

It's been the dominant form of client server communication for around 20
years,
It's implemented by browsers and servers on around 4 billion computers.

So you can keep pretending it's some new invention, and we can close this
issue

> I've not yet seen a good argument for not using standards, for this use
> case. I suppose that widespread adoption could be one such reason. But I
> think adoption is small, perhaps less than 0.01% of the social web? I guess
> Im asking what is the this should be a W3C recommendation and not a note,
> when it breaks interop with existing standards.
>
You clearly have a very personal definition of the meaning of Standards.

**Comment by melvincarvalho** [comment] 2016-05-25 07:40
@kevinmarks It's best to avoid words like 'pretend' when talking about other
people's actions and intentions. Good typically doesn't come of it...

**Comment by kevinmarks** [comment] 2016-05-25 07:49
I'm using "pretend" in the sense of "make a claim". Are you using
"standards" in the sense of "flags that are personal emblems to identify
participants in a battle"?

**Comment by sandhawke** [comment] 2016-05-25 12:08
@melvincarvalho , your argument that somehow form-encoding isn't "standard" or Webmention isn't "standards compliant" really feels quite absurd to me.

If you want to move forward with this, I think your best path is to make a specific proposal for the "small change" you have in mind, maybe as a fork of the Webmention CR draft, with the changes clearly highlighted.  Then write what you believe to be a consensus (NPOV) document enumerating very specifically the ways this proposed alternate version would make life better for people and the ways it would make life worse for people.

Also -- and maybe first -- try to think of reasons that would convince the current 20+ implementors to change their code to match your proposal.   My guess is you wont be able to convince even one of them.  For this to fly, you need to be able to convince the vast majority of them.   I've thought about this issue a lot, and I really don't think it's possible.

**Comment by melvincarvalho** [comment] 2016-05-26 01:18
Im not quite sure I know how to respond to this.  Let me ask first off, do you believe, in creating standards we should use URIs to name things?

**Comment by melvincarvalho** [comment] 2016-05-26 01:25
I think, in general, I am perhaps misunderstanding the difference between REC and Note, and I would be very happy to understand that better, or be pointed to something that can explain it better.  Im really quite happy for the webmenion ecosytem to be a note, but my, perhaps naive, understand of REC implies "this is how we should solve this kind of problem", which I am slightly more cautious about.  I would be happy to understand this better.

**Comment by sandhawke** [comment] 2016-05-26 03:30
> I'm not quite sure I know how to respond to this. Let me ask first off, do you believe, in creating standards we should use URIs to name things?

I believe using URIs to name things can be a useful tool in the effort to achieve decentralized extensibility.   The last 15+ years of experience with xmlns and xhtml and rdf has convinced me the practice is a mixed blessing and should be used with care.   In the current design of webmention, I don't see URIs for property names as justified.

It would be nice if webmention were more extensible, but URIs for property names would be little help in that, since the sender wouldn't know what vocabulary the receiver would be capable of handling.   Just sending stuff blindly an endpoint seems less-than-useful.     If it's not blind -- if there's a well known set of options (eg vouch) -- then we don't need URIs for it.

**Comment by sandhawke** [comment] 2016-05-26 03:37
> I think, in general, I am perhaps misunderstanding the difference between REC and Note, and I would be very happy to understand that better, or be pointed to something that can explain it better. Im really quite happy for the webmenion ecosytem to be a note, but my, perhaps naive, understand of REC implies "this is how we should solve this kind of problem", which I am slightly more cautious about. I would be happy to understand this better.

The difference is that with a Recommendation, a critical mass of the member organizations thought it was worthwhile, a Working Group thought it was work making a Recommendation, and the various Rec Track steps (like demonstrating interoperability) were followed.   That's commonly understood, I think, as meaning that Recommendations are more carefully thought out and more people are interested in them.

Webmention makes more sense as a Recommendation than a Note because people do seem eager to implement it, and folks are (it appears at present) happy to carry it through the Rec Track.

**Comment by melvincarvalho** [comment] 2016-05-26 09:05
@sandhawke thanks for explaining, that is very helpful!

So it seems to me that webmention can be solved in one of two ways.  One is by reusing existing W3C RECs such as JSON-LD, and the other is a bespoke method using form encoded variables, as is currently documented in the spec, and has a small implementation base, with a relatively large representation in this WG, that's not a criticism (all great movements start out small!), just trying to reflect the actual position.

Why should we not, at a minimum, show an existing standards compliant method be put forward in the spec text?  e.g. An example of how to do it with form encoded variables and an example using JSON.

Form encoded version:

    source=https://waterpigs.example/post-by-barnaby&
    target=https://aaronpk.example/post-by-aaron

JSON-LD version:

    {
      "@context": "http://www.w3.org/ns/webmention",
      "source": "https://waterpigs.example/post-by-barnaby",
      "target": "https://aaronpk.example/post-by-aaron"
    }

To the extent that webmention is "just a signaling protocol" that says to a server, "hey, look at this part of the web which you may not have seen before" you could imagine it working with a simple HTTP GET and query string parameters.  Typically query string parameters would not expect namespaces or contexts (but maybe we have become conditioned to think this).  But it seems a bit more than that, in that it can be extended it seems to more general cases.

**Comment by sandhawke** [comment] 2016-05-26 09:57
That's my option 2.    It makes implementating each receiver harder, because now it has to understand two syntaxes.    And what's the real benefit?  Can you express that benefit in some way all the current implementors will find compelling?    What can you say to them that will make them want to go back to their code and add json support?   And I your explanation don't make an appeal to authority, explain how it will benefit them.

**Comment by melvincarvalho** [comment] 2016-05-26 14:27
I think we're not really communicating.  Im trying to express the benefit of interop leading to growth in the network effect, and you dont find it compelling.  I guess about all I can say is that I respect your opinion, but mine differs.

**Comment by rhiaro** [comment] 2016-05-26 14:52
FWIW I wrote up a draft spec to bridge between webmention and LDP implementations.

https://github.com/rhiaro/wm-ldp/blob/master/index.md

The first half is what to do if you have a webmention implementation and want to talk to plain LDP servers. The second half (more relevant for you @melvincarvalho) is what to do if you have an LDP server or a Solid application and want to receive from / send to plain webmention implementations.

Both ends seem pretty straightforward to me, this isn't a huge gap to plug.

**Comment by akuckartz** [comment] 2016-05-26 14:58
@melvincarvalho If I understand the comments here correctly then people seem to be missing an explanation _how_ the proposed change would "lead to growth in the network effect". I think that this is a legitimate question.

**Comment by melvincarvalho** [comment] 2016-05-26 16:31
@akuckartz I would have thought that to be self evident.  Millions of sites are already using JSON-LD even though its only a couple of years old.  Large companies such as Google have said they like it.  Solid and other systems are using it.  And it's growing.  All these factors contribute to a network effect.

**Comment by akuckartz** [comment] 2016-05-26 16:59
@melvincarvalho You do not need to convince me that it would make sense to use LD everywhere. The task I see in this issue is to convince others that the proposed change to the webmention specification has a significant positive effect and that there are good reasons to assume that the size of that effect is larger than the effect due to the resulting cost of implementing the change.

(I have not had a really close look at webmention myself and therefore will not attempt to analyse  that currently.)

**Comment by melvincarvalho** [comment] 2016-05-26 17:19
The implementation change is tiny.  As a programmer I can say that.  In fact you'll probably get more tooling for free making the cost possibly even negative!

**Comment by akuckartz** [comment] 2016-05-26 17:19
Question: What would be the effect of _replacing_ the form encoded version by the JSON-LD version in the spec ?

**Comment by melvincarvalho** [comment] 2016-05-26 17:21
@akuckartz it's a good idea.  If someone has cycles to write it.  It would be a great guide for someone that wished to implement it that way.  Unfortunately I just have too many other projects I have to take care of at this time, or id volunteer.

**Comment by melvincarvalho** [comment] 2016-05-26 17:22
@rhiaro do you think you might want to have a go at the above, if you have time free? ^^  I hope im not imposing on you by asking :)

**Comment by aaronpk** [comment] 2016-05-26 17:24
I'm just going to point back to what @sandhawke said:

> Abandoning your early adopters before establishing a new user base means you have nobody.

The time to suggest a 100% breaking change to the spec has long passed. There is already a *lot* of written and deployed code that sends webmentions using form-encoded syntax. It's not a matter of simply making a "tiny" change to switch to JSON, since it will affect senders as well as receivers, some of which are using libraries on both sides, not to mention the fact that this software is deployed quite widely and in places where a single person can't even mandate that it be updated. Such is the situation when a spec gets widely implemented.

**Comment by aaronpk** [comment] 2016-05-26 17:25
I'm just going to point back to what @sandhawke said:

> Abandoning your early adopters before establishing a new user base means you have nobody.

The time to suggest a 100% breaking change to the spec has long passed. There is already a lot of written and deployed code that sends webmentions using form-encoded syntax. It's not a matter of simply making a "tiny" change to switch to JSON, since it will affect senders as well as receivers, some of which are using libraries on both sides, not to mention the fact that this software is deployed quite widely and in places where a single person can't even mandate that it be updated. Such is the situation when a spec gets widely implemented.

**Comment by akuckartz** [comment] 2016-05-26 17:36
@aaronpk I understand your view but that argument does not convince me. If the change of an unfinished specification would require a rather small change in the code of current implementations than I would not agree that it is a "100% breaking change".

**Comment by kevinmarks** [comment] 2016-05-26 18:14
@rhiaro's document https://github.com/rhiaro/wm-ldp/blob/master/index.md is a very useful contribution here.

I'm happy to stipulate that many people find RDF useful to represent things, and a way to map between its worldview and webmention is both helpful for them and useful for interop.
That does not mean that it should be mandated for everyone else to parse, any more than representations in MySQL, C++ classes or Elixir Records should be. 

Form encoding is the time-tested boundary between implementation structures that minimizes the exposed surface area. If you want to do something else, you are free to do so, but changing this spec will not change other people's code. This is documentation, not legislation. 
Saying "The implementation change is tiny." and "Unfortunately I just have too many other projects I have to take care of at this time, or id volunteer." does not make the case.

**Comment by tantek** [comment] 2016-05-26 18:14
@sandhawke this issue is rapidly going off-topic / growing beyond original scope / going in circles.

Per your comment in https://github.com/aaronpk/webmention/issues/39#issuecomment-221340025 there's no charter issue, and thus this issue should be closed.

If there are implementers that want to brainstorm extensions to webmention, whether JSON(LD) or otherwise, I encourage them to open new specific issues for those new feature requests (citing their existing implementations would be useful), which can be considered for a future version per the point you made "Well, back before Webmention went to CR, when it could have potentially been changed".

**Comment by akuckartz** [comment] 2016-05-26 18:25
@tantek It does not make sense to create a new issue when the current one can be used.

**Comment by aaronpk** [comment] 2016-05-26 18:26
This issue is called "No JSON based social syntax", which is totally unrelated to the request to convert the webmention POST request to JSON format.

**Comment by akuckartz** [comment] 2016-05-26 18:28
@aaronpk Sorry, but that is a bit like hair-splitting. This issue can be retitled appropriately.

**Comment by tantek** [comment] 2016-05-26 18:30
@akuckartz morphing issues is considered bad practice in issue tracking systems. This started (primarily) as a charter issue, that's been resolved. It is customary practice to encourage creation of new issue(s) for anything ancillary discovered as part of the discussion. 
In particular if you're interested in the specifics of how W3C uses / should use Github, I encourage you to join discussions elsewhere for that: https://www.w3.org/wiki/GitHub

**Comment by akuckartz** [comment] 2016-05-26 18:49
I agree that it is very bad that this issue was raised so late (although have heard vocal concerns a long time ego).

But the core of this issue from the beginning was about the fact that JSON(-LD) is not supported/used by the current version of the webmention specification. That certainly was not "ancillary discovered as part of the discussion".

@tantek Thanks for the link, but I did not find anything relevant for the current issue there.

**Comment by sandhawke** [comment] 2016-05-26 18:57
@akuckartz wrote
> If the change of an unfinished specification would require a rather small change in the code of current implementations than I would not agree that it is a "100% breaking change".

I think a reasonable definition of "100% breaking change" (for a spec) is: a change which makes 100% of the implementations no longer conform to the spec.    Switching the webmention syntax from form-encoding to JSON-LD would therefore be a 100% breaking change.   Every single implementation would have to be modified (and all at exactly the same time).    Mandating that receivers accept JSON-LD would be 100% breaking for receivers (unless there are some that currently accept JSON-LD?   Maybe @rhiaro's does), which would probably be something like 33% breaking, assuming there are twice as many receiver implementations as sender implementations. 

Rather than split off another issue, I suggest we close this one.   @melvincarvalho @akuckartz do you want to keep talking about this?   If so, can you raise another issue, specifically on the proposal that mentions payload syntax be JSON-LD instead of Form-Encoding, or in addition to Form-Encoding?   (I suggest you pick one.   I'm pretty sure I've already explained why neither one is tenable, but we can keep talking about it.)

**Comment by aaronpk** [comment] 2016-05-26 19:28
Based on the requests from a chair and w3c team contact, I am closing this issue. @melvincarvalho @akuckartz please see the suggestions above for ways to pick up this discussion again if you feel it is necessary. In the future, please keep the discussions in these issues focused and on the original topic.

**Closed by aaronpk** 2016-05-26 19:28 UTC

**Comment by akuckartz** [comment] 2016-05-26 19:36
For the record: I strongly object to the claim that the contributions were not focused on the original topic.

**Comment by melvincarvalho** [comment] 2016-05-26 21:36
Also strongly object.

> I agree that it is very bad that this issue was raised so late (although have heard vocal concerns a long time ego).

I raised this in July of 2015 on the mailing list.

**Comment by melvincarvalho** [comment] 2016-05-26 21:39
FWIW one of the main reasons I stopped following this closely was that both @aaronpk and @tantek were closing issues prematurely in a heavy handed way.  At one point I was on the admin group of github and I was removed unilateral, without explanation.  While issues were closed down and several members of the WG wanted to discuss further.  This process is a joke.  All I can say is that I object in the strongest possibly way.

**Comment by sandhawke** [comment] 2016-05-26 21:46
We're just asking you to keep separate issues in separate issues.    Can you please do that?    Since the original topic of this thread was about the charter, let's use it for that.    And, as I said, put other issues in other github issues.   I can open it for you if you want, but the records are clearer if the person opening the issue is one who supports some change.

**Comment by rhiaro** [comment] 2016-05-26 21:46
@melvincarvalho By the way, the working group does also have another draft on the rec-track that contains a notification mechanism which *does* use JSON-LD as the payload (ActivityPub). So rather than objecting to a spec that doesn't meet your needs you might have a better time helping out a spec that does, so we get the various alternatives to CR. We all agreed to agree there's no one-size-fits-all and to go forth with different approaches for exactly this reason.

SWP (https://w3c-social.github.io/social-web-protocols/respec.html, in progress) explains when you might choose one over another. I'm also happy to design and implement small bridges between them as appropriate. Pitching them against each other in a winner-takes-all battle of the specs is not something I'm interested in however, as that's just not how life, and the web, works.

**Comment by sandhawke** [comment] 2016-05-27 03:53
@akuckartz 

The original topic was 

>  No JSON based social syntax #39 

> The WG charter states:

>>  A JSON-based syntax to allow the transfer of social information

> Yet I was unable to locate any JSON based examples in the text (tho perhaps I missed something)

> Could this be made available for review?

To paraphrase, the original topic was about a potential charter violation.   I addressed that point in comment https://github.com/aaronpk/webmention/issues/39#issuecomment-221340025 clarifying that, in fact, there is a JSON based social syntax, and it's called AS2.   I believe that should have been sufficient to close this issue.    No one has said any more about that.     

Meanwhile, there is a similar but critically distinct issue about whether Webmention should use JSON.  That's most of what we've been talking about in this github issue, but it's a different topic.

I'm sorry I wasn't more strict from the beginning about keeping discussion to **only** be about the charter question.

Given how they've been jumbled together so far, I'm not actually sure the best way forward, as far as github issue numbers.    It's pretty important that we separate them, especially if their outcomes are different.

**Comment by lehors** [comment] 2016-05-27 05:10
@sandhawke It's very simple: You create a new issue in which you point out that the discussion started here, with a reference to this issue #. Done.
This happens all the time on github.

**Comment by sandhawke** [comment] 2016-05-27 12:28
Fine, I had my reasons, but, .... done.

**Comment by lehors** [comment] 2016-05-27 14:57
@sandhawke, I didn't mean that you, personally, had to do it. I just gave you the answer to the question you raised about how to handle the situation from a github point of view.

**Comment by tantek** [comment] 2016-05-31 13:05
@melvincarvalho wrote:
> FWIW one of the main reasons I stopped following this closely was that both @aaronpk and @tantek were closing issues prematurely in a heavy handed way. 
Melvin, this is off-topic, and frankly, rude. If there are specific issues resolutions that you objected to, you should object in those issues. If you have a formal objection (W3C term: https://www.w3.org/2015/Process-20150901/#WGArchiveMinorityViews ) to a specific issue, you should note that in that issue literally as a "Formal Objection".

> At one point I was on the admin group of github and I was removed unilateral, without explanation.
Again, unrelated to this issue. If you have an issue with any of the process in the working group, raise it to the chairs and team contact as a "Process issue", in one of our general forums, e.g. telcon, IRC, or even email and at least one of them (chairs or team contact) will address it.

> While issues were closed down and several members of the WG wanted to discuss further.
See above about specific issues.

> This process is a joke.
See above about raise anything regarding process to the chairs and team contact, not in an unrelated Github issue.

> All I can say is that I object in the strongest possibly way.
If you actually have a "formal objection" (W3C term, link above), you have to say so literally so we can record it as such.
